// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package omega

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OmegaServiceClient is the client API for OmegaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OmegaServiceClient interface {
	Pub(ctx context.Context, in *PubRequest, opts ...grpc.CallOption) (*PubResponse, error)
	Subscribe(ctx context.Context, in *SubscribeReq, opts ...grpc.CallOption) (*SubscribeRsp, error)
}

type omegaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOmegaServiceClient(cc grpc.ClientConnInterface) OmegaServiceClient {
	return &omegaServiceClient{cc}
}

func (c *omegaServiceClient) Pub(ctx context.Context, in *PubRequest, opts ...grpc.CallOption) (*PubResponse, error) {
	out := new(PubResponse)
	err := c.cc.Invoke(ctx, "/omega.OmegaService/Pub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *omegaServiceClient) Subscribe(ctx context.Context, in *SubscribeReq, opts ...grpc.CallOption) (*SubscribeRsp, error) {
	out := new(SubscribeRsp)
	err := c.cc.Invoke(ctx, "/omega.OmegaService/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OmegaServiceServer is the server API for OmegaService service.
// All implementations must embed UnimplementedOmegaServiceServer
// for forward compatibility
type OmegaServiceServer interface {
	Pub(context.Context, *PubRequest) (*PubResponse, error)
	Subscribe(context.Context, *SubscribeReq) (*SubscribeRsp, error)
	mustEmbedUnimplementedOmegaServiceServer()
}

// UnimplementedOmegaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOmegaServiceServer struct {
}

func (UnimplementedOmegaServiceServer) Pub(context.Context, *PubRequest) (*PubResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pub not implemented")
}
func (UnimplementedOmegaServiceServer) Subscribe(context.Context, *SubscribeReq) (*SubscribeRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedOmegaServiceServer) mustEmbedUnimplementedOmegaServiceServer() {}

// UnsafeOmegaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OmegaServiceServer will
// result in compilation errors.
type UnsafeOmegaServiceServer interface {
	mustEmbedUnimplementedOmegaServiceServer()
}

func RegisterOmegaServiceServer(s grpc.ServiceRegistrar, srv OmegaServiceServer) {
	s.RegisterService(&OmegaService_ServiceDesc, srv)
}

func _OmegaService_Pub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmegaServiceServer).Pub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/omega.OmegaService/Pub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmegaServiceServer).Pub(ctx, req.(*PubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OmegaService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmegaServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/omega.OmegaService/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmegaServiceServer).Subscribe(ctx, req.(*SubscribeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OmegaService_ServiceDesc is the grpc.ServiceDesc for OmegaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OmegaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omega.OmegaService",
	HandlerType: (*OmegaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pub",
			Handler:    _OmegaService_Pub_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _OmegaService_Subscribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "omega.proto",
}
