// Code generated by protoc-gen-go. DO NOT EDIT.
// source: omega.proto

package server

/*
protoc -I=$SRC_DIR --go_out=$DST_DIR $SRC_DIR/omega.proto
protoc -I=. --go_out=. omega.proto
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PubRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topic_name,json=topicName" json:"topic_name,omitempty"`
	Partition            uint32   `protobuf:"varint,3,opt,name=partition" json:"partition,omitempty"`
	HashCode             uint64   `protobuf:"varint,4,opt,name=hash_code,json=hashCode" json:"hash_code,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PubRequest) Reset()         { *m = PubRequest{} }
func (m *PubRequest) String() string { return proto.CompactTextString(m) }
func (*PubRequest) ProtoMessage()    {}
func (*PubRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_08a9fb248ede2058, []int{0}
}
func (m *PubRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubRequest.Unmarshal(m, b)
}
func (m *PubRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubRequest.Marshal(b, m, deterministic)
}
func (dst *PubRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubRequest.Merge(dst, src)
}
func (m *PubRequest) XXX_Size() int {
	return xxx_messageInfo_PubRequest.Size(m)
}
func (m *PubRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PubRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PubRequest proto.InternalMessageInfo

func (m *PubRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PubRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *PubRequest) GetPartition() uint32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *PubRequest) GetHashCode() uint64 {
	if m != nil {
		return m.HashCode
	}
	return 0
}

func (m *PubRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PubResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PubResponse) Reset()         { *m = PubResponse{} }
func (m *PubResponse) String() string { return proto.CompactTextString(m) }
func (*PubResponse) ProtoMessage()    {}
func (*PubResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_08a9fb248ede2058, []int{1}
}
func (m *PubResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubResponse.Unmarshal(m, b)
}
func (m *PubResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubResponse.Marshal(b, m, deterministic)
}
func (dst *PubResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubResponse.Merge(dst, src)
}
func (m *PubResponse) XXX_Size() int {
	return xxx_messageInfo_PubResponse.Size(m)
}
func (m *PubResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PubResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PubResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PubRequest)(nil), "omega.PubRequest")
	proto.RegisterType((*PubResponse)(nil), "omega.PubResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OmegaServiceClient is the client API for OmegaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OmegaServiceClient interface {
	Pub(ctx context.Context, in *PubRequest, opts ...grpc.CallOption) (*PubResponse, error)
}

type omegaServiceClient struct {
	cc *grpc.ClientConn
}

func NewOmegaServiceClient(cc *grpc.ClientConn) OmegaServiceClient {
	return &omegaServiceClient{cc}
}

func (c *omegaServiceClient) Pub(ctx context.Context, in *PubRequest, opts ...grpc.CallOption) (*PubResponse, error) {
	out := new(PubResponse)
	err := c.cc.Invoke(ctx, "/omega.OmegaService/Pub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OmegaServiceServer is the server API for OmegaService service.
type OmegaServiceServer interface {
	Pub(context.Context, *PubRequest) (*PubResponse, error)
}

func RegisterOmegaServiceServer(s *grpc.Server, srv OmegaServiceServer) {
	s.RegisterService(&_OmegaService_serviceDesc, srv)
}

func _OmegaService_Pub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OmegaServiceServer).Pub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/omega.OmegaService/Pub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OmegaServiceServer).Pub(ctx, req.(*PubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OmegaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "omega.OmegaService",
	HandlerType: (*OmegaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pub",
			Handler:    _OmegaService_Pub_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "omega.proto",
}

func init() { proto.RegisterFile("omega.proto", fileDescriptor_omega_08a9fb248ede2058) }

var fileDescriptor_omega_08a9fb248ede2058 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0x3d, 0x4e, 0xc4, 0x30,
	0x10, 0x05, 0x60, 0xcc, 0x66, 0x11, 0x99, 0xdd, 0x2d, 0x98, 0xca, 0xe2, 0x47, 0x8a, 0x52, 0xa5,
	0x4a, 0x01, 0x3d, 0x0d, 0x3d, 0xac, 0xcc, 0x01, 0x56, 0x13, 0x67, 0x44, 0x5c, 0x24, 0x63, 0x62,
	0x87, 0xb3, 0x70, 0x5c, 0x64, 0xa7, 0x08, 0x9d, 0xfd, 0x8d, 0x9e, 0xf4, 0x1e, 0x1c, 0x64, 0xe4,
	0x2f, 0x6a, 0xfd, 0x2c, 0x51, 0x70, 0x9f, 0x3f, 0xf5, 0xaf, 0x02, 0x38, 0x2f, 0x9d, 0xe1, 0xef,
	0x85, 0x43, 0xc4, 0x47, 0x28, 0x27, 0x1a, 0x39, 0x78, 0xb2, 0xac, 0x55, 0xa5, 0x9a, 0xd2, 0x6c,
	0x80, 0x4f, 0x00, 0x51, 0xbc, 0xb3, 0x97, 0x44, 0xfa, 0x7a, 0x3d, 0x67, 0x79, 0xa7, 0x91, 0x53,
	0xd8, 0xd3, 0x1c, 0x5d, 0x74, 0x32, 0xe9, 0x5d, 0xa5, 0x9a, 0x93, 0xd9, 0x00, 0x1f, 0xa0, 0x1c,
	0x28, 0x0c, 0x17, 0x2b, 0x3d, 0xeb, 0xa2, 0x52, 0x4d, 0x61, 0x6e, 0x13, 0xbc, 0x49, 0xcf, 0x88,
	0x50, 0xf4, 0x14, 0x49, 0xef, 0x2b, 0xd5, 0x1c, 0x4d, 0x7e, 0xd7, 0x27, 0x38, 0xe4, 0x66, 0xc1,
	0xcb, 0x14, 0xf8, 0xf9, 0x15, 0x8e, 0x1f, 0xa9, 0xf2, 0x27, 0xcf, 0x3f, 0xce, 0x32, 0xb6, 0xb0,
	0x3b, 0x2f, 0x1d, 0xde, 0xb5, 0xeb, 0xaa, 0x6d, 0xc4, 0x3d, 0xfe, 0xa7, 0x35, 0x5d, 0x5f, 0x75,
	0x37, 0x79, 0xf7, 0xcb, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0xeb, 0x4c, 0x30, 0x06, 0x01,
	0x00, 0x00,
}
