// Code generated by protoc-gen-go. DO NOT EDIT.
// source: omega.proto

package alpha // import "github.com/ml444/scheduler/pb/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// strategy
type Policy int32

const (
	Policy_PolicyConcurrence Policy = 0
	Policy_PolicySerial      Policy = 1
)

var Policy_name = map[int32]string{
	0: "PolicyConcurrence",
	1: "PolicySerial",
}
var Policy_value = map[string]int32{
	"PolicyConcurrence": 0,
	"PolicySerial":      1,
}

func (x Policy) String() string {
	return proto.EnumName(Policy_name, int32(x))
}
func (Policy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_omega_ad6899aca5d6d0f3, []int{0}
}

type PubReq struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topic_name,json=topicName" json:"topic_name,omitempty"`
	Partition            uint32   `protobuf:"varint,3,opt,name=partition" json:"partition,omitempty"`
	HashCode             uint64   `protobuf:"varint,4,opt,name=hash_code,json=hashCode" json:"hash_code,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PubReq) Reset()         { *m = PubReq{} }
func (m *PubReq) String() string { return proto.CompactTextString(m) }
func (*PubReq) ProtoMessage()    {}
func (*PubReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_ad6899aca5d6d0f3, []int{0}
}
func (m *PubReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubReq.Unmarshal(m, b)
}
func (m *PubReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubReq.Marshal(b, m, deterministic)
}
func (dst *PubReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubReq.Merge(dst, src)
}
func (m *PubReq) XXX_Size() int {
	return xxx_messageInfo_PubReq.Size(m)
}
func (m *PubReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PubReq.DiscardUnknown(m)
}

var xxx_messageInfo_PubReq proto.InternalMessageInfo

func (m *PubReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PubReq) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *PubReq) GetPartition() uint32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *PubReq) GetHashCode() uint64 {
	if m != nil {
		return m.HashCode
	}
	return 0
}

func (m *PubReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PubRsp struct {
	Status               int32    `protobuf:"zigzag32,1,opt,name=status" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PubRsp) Reset()         { *m = PubRsp{} }
func (m *PubRsp) String() string { return proto.CompactTextString(m) }
func (*PubRsp) ProtoMessage()    {}
func (*PubRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_ad6899aca5d6d0f3, []int{1}
}
func (m *PubRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubRsp.Unmarshal(m, b)
}
func (m *PubRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubRsp.Marshal(b, m, deterministic)
}
func (dst *PubRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubRsp.Merge(dst, src)
}
func (m *PubRsp) XXX_Size() int {
	return xxx_messageInfo_PubRsp.Size(m)
}
func (m *PubRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PubRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PubRsp proto.InternalMessageInfo

func (m *PubRsp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PubRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SubReq struct {
	ClientId  string `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	Topic     string `protobuf:"bytes,3,opt,name=topics" json:"topics,omitempty"`
	Group     string `protobuf:"bytes,4,opt,name=group" json:"group,omitempty"`
	//  uint32 max_retry_count = 5;
	//  uint32 max_timeout = 6;
	//  uint32 retry_interval_ms =7;
	//  uint32 item_lifetime_in_Queue = 8;
	Policy               Policy   `protobuf:"varint,9,opt,name=policy,enum=omega.Policy" json:"policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *SubReq) Reset()         { *m = SubReq{} }
func (m *SubReq) String() string { return proto.CompactTextString(m) }
func (*SubReq) ProtoMessage()    {}
func (*SubReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_ad6899aca5d6d0f3, []int{2}
}
func (m *SubReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubReq.Unmarshal(m, b)
}
func (m *SubReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubReq.Marshal(b, m, deterministic)
}
func (dst *SubReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubReq.Merge(dst, src)
}
func (m *SubReq) XXX_Size() int {
	return xxx_messageInfo_SubReq.Size(m)
}
func (m *SubReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SubReq.DiscardUnknown(m)
}

var xxx_messageInfo_SubReq proto.InternalMessageInfo

func (m *SubReq) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *SubReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SubReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SubReq) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *SubReq) GetPolicy() Policy {
	if m != nil {
		return m.Policy
	}
	return Policy_PolicyConcurrence
}

type SubRsp struct {
	Status               int32    `protobuf:"zigzag32,1,opt,name=status" json:"status,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *SubRsp) Reset()         { *m = SubRsp{} }
func (m *SubRsp) String() string { return proto.CompactTextString(m) }
func (*SubRsp) ProtoMessage()    {}
func (*SubRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_ad6899aca5d6d0f3, []int{3}
}
func (m *SubRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubRsp.Unmarshal(m, b)
}
func (m *SubRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubRsp.Marshal(b, m, deterministic)
}
func (dst *SubRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubRsp.Merge(dst, src)
}
func (m *SubRsp) XXX_Size() int {
	return xxx_messageInfo_SubRsp.Size(m)
}
func (m *SubRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SubRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SubRsp proto.InternalMessageInfo

func (m *SubRsp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SubRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Topic struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topic_name,json=topicName" json:"topic_name,omitempty"`
	Partitions           uint32   `protobuf:"varint,3,opt,name=partitions" json:"partitions,omitempty"`
	Priority             uint32   `protobuf:"varint,4,opt,name=priority" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_ad6899aca5d6d0f3, []int{4}
}
func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (dst *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(dst, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Topic) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *Topic) GetPartitions() uint32 {
	if m != nil {
		return m.Partitions
	}
	return 0
}

func (m *Topic) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type SubCfg struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topics" json:"topics,omitempty"`
	Group                string   `protobuf:"bytes,3,opt,name=group" json:"group,omitempty"`
	Version              uint32   `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	MaxRetryCount        uint32   `protobuf:"varint,5,opt,name=max_retry_count,json=maxRetryCount" json:"max_retry_count,omitempty"`
	MaxTimeout           uint32   `protobuf:"varint,6,opt,name=max_timeout,json=maxTimeout" json:"max_timeout,omitempty"`
	RetryIntervalMs      uint32   `protobuf:"varint,7,opt,name=retry_interval_ms,json=retryIntervalMs" json:"retry_interval_ms,omitempty"`
	ItemLifetimeInQueue  uint32   `protobuf:"varint,8,opt,name=item_lifetime_in_queue,json=itemLifetimeInQueue" json:"item_lifetime_in_queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *SubCfg) Reset()         { *m = SubCfg{} }
func (m *SubCfg) String() string { return proto.CompactTextString(m) }
func (*SubCfg) ProtoMessage()    {}
func (*SubCfg) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_ad6899aca5d6d0f3, []int{5}
}
func (m *SubCfg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubCfg.Unmarshal(m, b)
}
func (m *SubCfg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubCfg.Marshal(b, m, deterministic)
}
func (dst *SubCfg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubCfg.Merge(dst, src)
}
func (m *SubCfg) XXX_Size() int {
	return xxx_messageInfo_SubCfg.Size(m)
}
func (m *SubCfg) XXX_DiscardUnknown() {
	xxx_messageInfo_SubCfg.DiscardUnknown(m)
}

var xxx_messageInfo_SubCfg proto.InternalMessageInfo

func (m *SubCfg) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SubCfg) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SubCfg) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *SubCfg) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SubCfg) GetMaxRetryCount() uint32 {
	if m != nil {
		return m.MaxRetryCount
	}
	return 0
}

func (m *SubCfg) GetMaxTimeout() uint32 {
	if m != nil {
		return m.MaxTimeout
	}
	return 0
}

func (m *SubCfg) GetRetryIntervalMs() uint32 {
	if m != nil {
		return m.RetryIntervalMs
	}
	return 0
}

func (m *SubCfg) GetItemLifetimeInQueue() uint32 {
	if m != nil {
		return m.ItemLifetimeInQueue
	}
	return 0
}

type Response struct {
	Status               int32    `protobuf:"zigzag32,1,opt,name=status" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_ad6899aca5d6d0f3, []int{6}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ConsumeReq struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topics" json:"topics,omitempty"`
	Group                string   `protobuf:"bytes,3,opt,name=group" json:"group,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
	Sequence             uint64   `protobuf:"varint,5,opt,name=sequence" json:"sequence,omitempty"`
	IsRetry              bool     `protobuf:"varint,6,opt,name=is_retry,json=isRetry" json:"is_retry,omitempty"`
	IgnoreRetryCount     bool     `protobuf:"varint,7,opt,name=ignore_retry_count,json=ignoreRetryCount" json:"ignore_retry_count,omitempty"`
	RetryIntervalMs      int64    `protobuf:"zigzag64,8,opt,name=retry_interval_ms,json=retryIntervalMs" json:"retry_interval_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ConsumeReq) Reset()         { *m = ConsumeReq{} }
func (m *ConsumeReq) String() string { return proto.CompactTextString(m) }
func (*ConsumeReq) ProtoMessage()    {}
func (*ConsumeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_ad6899aca5d6d0f3, []int{7}
}
func (m *ConsumeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeReq.Unmarshal(m, b)
}
func (m *ConsumeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeReq.Marshal(b, m, deterministic)
}
func (dst *ConsumeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeReq.Merge(dst, src)
}
func (m *ConsumeReq) XXX_Size() int {
	return xxx_messageInfo_ConsumeReq.Size(m)
}
func (m *ConsumeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeReq proto.InternalMessageInfo

func (m *ConsumeReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ConsumeReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *ConsumeReq) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *ConsumeReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ConsumeReq) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ConsumeReq) GetIsRetry() bool {
	if m != nil {
		return m.IsRetry
	}
	return false
}

func (m *ConsumeReq) GetIgnoreRetryCount() bool {
	if m != nil {
		return m.IgnoreRetryCount
	}
	return false
}

func (m *ConsumeReq) GetRetryIntervalMs() int64 {
	if m != nil {
		return m.RetryIntervalMs
	}
	return 0
}

type ConsumeRsp struct {
	Partition            uint32   `protobuf:"varint,2,opt,name=partition" json:"partition,omitempty"`
	Sequence             uint64   `protobuf:"varint,3,opt,name=sequence" json:"sequence,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	RetryCount           uint32   `protobuf:"varint,5,opt,name=retry_count,json=retryCount" json:"retry_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ConsumeRsp) Reset()         { *m = ConsumeRsp{} }
func (m *ConsumeRsp) String() string { return proto.CompactTextString(m) }
func (*ConsumeRsp) ProtoMessage()    {}
func (*ConsumeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_ad6899aca5d6d0f3, []int{8}
}
func (m *ConsumeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeRsp.Unmarshal(m, b)
}
func (m *ConsumeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeRsp.Marshal(b, m, deterministic)
}
func (dst *ConsumeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeRsp.Merge(dst, src)
}
func (m *ConsumeRsp) XXX_Size() int {
	return xxx_messageInfo_ConsumeRsp.Size(m)
}
func (m *ConsumeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeRsp proto.InternalMessageInfo

func (m *ConsumeRsp) GetPartition() uint32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *ConsumeRsp) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ConsumeRsp) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ConsumeRsp) GetRetryCount() uint32 {
	if m != nil {
		return m.RetryCount
	}
	return 0
}

func init() {
	proto.RegisterType((*PubReq)(nil), "omega.PubReq")
	proto.RegisterType((*PubRsp)(nil), "omega.PubRsp")
	proto.RegisterType((*SubReq)(nil), "omega.SubReq")
	proto.RegisterType((*SubRsp)(nil), "omega.SubRsp")
	proto.RegisterType((*Topic)(nil), "omega.Topic")
	proto.RegisterType((*SubCfg)(nil), "omega.SubCfg")
	proto.RegisterType((*Response)(nil), "omega.Response")
	proto.RegisterType((*ConsumeReq)(nil), "omega.ConsumeReq")
	proto.RegisterType((*ConsumeRsp)(nil), "omega.ConsumeRsp")
	proto.RegisterEnum("omega.Policy", Policy_name, Policy_value)
}

func init() { proto.RegisterFile("omega.proto", fileDescriptor_omega_ad6899aca5d6d0f3) }

var fileDescriptor_omega_ad6899aca5d6d0f3 = []byte{
	// 731 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x5d, 0x6f, 0xd3, 0x3c,
	0x14, 0x5e, 0xfa, 0x99, 0x9c, 0xb5, 0xef, 0x5a, 0xbf, 0x30, 0x85, 0x8e, 0x8f, 0x2a, 0xd2, 0x50,
	0x35, 0x60, 0x85, 0x6d, 0x70, 0x81, 0xb8, 0x19, 0xbd, 0x9a, 0xc4, 0xc7, 0x48, 0x77, 0xc5, 0x4d,
	0xe4, 0x26, 0x5e, 0x6b, 0xd1, 0xc4, 0x99, 0xed, 0x4c, 0x9b, 0xb8, 0xe1, 0x47, 0xa0, 0xfd, 0x4d,
	0x7e, 0x01, 0x12, 0xb2, 0x9d, 0xb6, 0x69, 0x37, 0x31, 0x01, 0x77, 0x7d, 0x9e, 0x73, 0x62, 0x9f,
	0xe7, 0x39, 0xe7, 0xb8, 0xb0, 0xce, 0x62, 0x32, 0xc6, 0xbb, 0x29, 0x67, 0x92, 0xa1, 0xaa, 0x06,
	0xde, 0x77, 0x0b, 0x6a, 0xc7, 0xd9, 0xc8, 0x27, 0x67, 0xe8, 0x3e, 0x38, 0x09, 0x8e, 0x89, 0x48,
	0x71, 0x48, 0x5c, 0xab, 0x6b, 0xf5, 0x1c, 0x7f, 0x41, 0xa0, 0x07, 0x00, 0x92, 0xa5, 0x34, 0x0c,
	0x14, 0xe5, 0x96, 0x4c, 0x58, 0x33, 0x1f, 0x70, 0x4c, 0xd4, 0xc7, 0x29, 0xe6, 0x92, 0x4a, 0xca,
	0x12, 0xb7, 0xdc, 0xb5, 0x7a, 0x4d, 0x7f, 0x41, 0xa0, 0x2d, 0x70, 0x26, 0x58, 0x4c, 0x82, 0x90,
	0x45, 0xc4, 0xad, 0x74, 0xad, 0x5e, 0xc5, 0xb7, 0x15, 0x31, 0x60, 0x11, 0x41, 0x08, 0x2a, 0x11,
	0x96, 0xd8, 0xad, 0x76, 0xad, 0x5e, 0xc3, 0xd7, 0xbf, 0xbd, 0xd7, 0xa6, 0x2a, 0x91, 0xa2, 0x4d,
	0xa8, 0x09, 0x89, 0x65, 0x26, 0x74, 0x49, 0x6d, 0x3f, 0x47, 0xc8, 0x85, 0x7a, 0x4c, 0x84, 0xc0,
	0xe3, 0x59, 0x31, 0x33, 0xe8, 0x5d, 0x59, 0x50, 0x1b, 0x1a, 0x49, 0x5b, 0xe0, 0x84, 0x53, 0x4a,
	0x12, 0x19, 0xd0, 0x28, 0x97, 0x64, 0x1b, 0xe2, 0x28, 0x5a, 0xd6, 0x5b, 0x5a, 0xd5, 0x7b, 0x07,
	0xaa, 0x5a, 0x9d, 0x16, 0xe3, 0xf8, 0x06, 0x28, 0x76, 0xcc, 0x59, 0x96, 0x6a, 0x11, 0x8e, 0x6f,
	0x00, 0xda, 0x86, 0x5a, 0xca, 0xa6, 0x34, 0xbc, 0x74, 0x9d, 0xae, 0xd5, 0xfb, 0x6f, 0xaf, 0xb9,
	0x6b, 0x9c, 0x3e, 0xd6, 0xa4, 0x9f, 0x07, 0xbd, 0x57, 0xa6, 0xae, 0xdf, 0x88, 0xd2, 0x97, 0x7e,
	0x21, 0x49, 0x5e, 0x8e, 0x01, 0xde, 0x37, 0x0b, 0xaa, 0x27, 0xfa, 0xfa, 0x7f, 0x6a, 0xd1, 0x43,
	0x80, 0x79, 0x47, 0x44, 0xde, 0xa3, 0x02, 0x83, 0x3a, 0x60, 0xa7, 0x9c, 0x32, 0x4e, 0xe5, 0xa5,
	0x96, 0xd7, 0xf4, 0xe7, 0xd8, 0xbb, 0x2a, 0xe9, 0xda, 0x07, 0xa7, 0xe3, 0x5b, 0x6a, 0x98, 0xdb,
	0x56, 0xba, 0xd1, 0xb6, 0x72, 0xd1, 0x36, 0x17, 0xea, 0xe7, 0x84, 0x0b, 0x35, 0x31, 0xe6, 0xbe,
	0x19, 0x44, 0x8f, 0x61, 0x23, 0xc6, 0x17, 0x01, 0x27, 0x92, 0x5f, 0x06, 0x21, 0xcb, 0x12, 0xa9,
	0xa7, 0xa3, 0xe9, 0x37, 0x63, 0x7c, 0xe1, 0x2b, 0x76, 0xa0, 0x48, 0xf4, 0x08, 0xd6, 0x55, 0x9e,
	0xa4, 0x31, 0x61, 0x99, 0x74, 0x6b, 0x46, 0x53, 0x8c, 0x2f, 0x4e, 0x0c, 0x83, 0x76, 0xa0, 0x6d,
	0x0e, 0xa1, 0x89, 0x24, 0xfc, 0x1c, 0x4f, 0x83, 0x58, 0xb8, 0x75, 0x9d, 0xb6, 0xa1, 0x03, 0x47,
	0x39, 0xff, 0x5e, 0xa0, 0x7d, 0xd8, 0xa4, 0x92, 0xc4, 0xc1, 0x94, 0x9e, 0x12, 0x75, 0x62, 0x40,
	0x93, 0xe0, 0x2c, 0x23, 0x19, 0x71, 0x6d, 0xfd, 0xc1, 0xff, 0x2a, 0xfa, 0x2e, 0x0f, 0x1e, 0x25,
	0x9f, 0x54, 0xc8, 0x7b, 0x03, 0xb6, 0x4f, 0x44, 0xca, 0x12, 0x41, 0xfe, 0x62, 0x54, 0x7f, 0x5a,
	0x00, 0x03, 0x96, 0x88, 0x2c, 0x26, 0xb7, 0x6f, 0xe0, 0x9f, 0x58, 0x3b, 0x1f, 0xa4, 0x4a, 0x61,
	0x90, 0x54, 0x87, 0x05, 0x39, 0xcb, 0x48, 0x12, 0x12, 0xed, 0x67, 0xc5, 0x9f, 0x63, 0x74, 0x0f,
	0x6c, 0x2a, 0x8c, 0xe3, 0xda, 0x47, 0xdb, 0xaf, 0x53, 0xa1, 0xad, 0x46, 0x4f, 0x01, 0xd1, 0x71,
	0xc2, 0x38, 0x59, 0x6a, 0x48, 0x5d, 0x27, 0xb5, 0x4c, 0xa4, 0xd0, 0x93, 0x1b, 0x2d, 0x57, 0x0e,
	0xa2, 0x6b, 0x96, 0x7b, 0x5f, 0x17, 0xf2, 0x45, 0xba, 0xfc, 0x86, 0x94, 0x56, 0xdf, 0x90, 0x62,
	0xf1, 0xe5, 0x95, 0xe2, 0x67, 0x4f, 0x48, 0x65, 0xf1, 0x84, 0xa8, 0xd9, 0xb8, 0x3e, 0x3f, 0xc0,
	0xe7, 0x85, 0xee, 0xbc, 0x80, 0x9a, 0x59, 0x50, 0x74, 0x17, 0xda, 0xe6, 0xd7, 0x80, 0x25, 0x61,
	0xc6, 0xb9, 0x3a, 0xb3, 0xb5, 0x86, 0x5a, 0xd0, 0x30, 0xf4, 0x90, 0x70, 0x8a, 0xa7, 0x2d, 0x6b,
	0xef, 0x87, 0x05, 0x8d, 0x8f, 0x6a, 0xb5, 0x87, 0x84, 0x9f, 0xd3, 0x90, 0xa0, 0x6d, 0x28, 0x1f,
	0x67, 0x23, 0x34, 0x5f, 0x78, 0xfd, 0xec, 0x74, 0x8a, 0x50, 0xa4, 0xde, 0x9a, 0x4a, 0x1b, 0x16,
	0xd2, 0x86, 0xcb, 0x69, 0xc3, 0x59, 0xda, 0x13, 0xb0, 0x0f, 0xa3, 0xc8, 0xac, 0x7a, 0x23, 0x0f,
	0x6a, 0xd4, 0xd9, 0xc8, 0xd1, 0x6c, 0xd6, 0xbc, 0x35, 0xf4, 0x0c, 0x9c, 0xc3, 0x28, 0xca, 0x97,
	0xb2, 0x70, 0xd4, 0xe0, 0x74, 0x7c, 0x53, 0xfa, 0x4b, 0xa8, 0xe7, 0x56, 0xa3, 0x76, 0x1e, 0x5d,
	0x4c, 0x5e, 0x67, 0x95, 0x52, 0xe5, 0xf4, 0xac, 0xe7, 0xd6, 0x5b, 0xef, 0x73, 0x77, 0x4c, 0xe5,
	0x24, 0x1b, 0xed, 0x86, 0x2c, 0xee, 0xc7, 0xd3, 0x83, 0x83, 0x83, 0xbe, 0x08, 0x27, 0x24, 0xca,
	0xa6, 0x84, 0xf7, 0xd3, 0x51, 0x3f, 0x1d, 0x8d, 0x6a, 0xfa, 0x1f, 0x65, 0xff, 0x57, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xce, 0xa0, 0x8e, 0x2c, 0x60, 0x06, 0x00, 0x00,
}
