// Code generated by protoc-gen-go. DO NOT EDIT.
// source: omega.proto

package pb // import "github.com/ml444/scheduler/pb/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// strategy
type Policy int32

const (
	Policy_PolicyConcurrence Policy = 0
	Policy_PolicySerial      Policy = 1
)

var Policy_name = map[int32]string{
	0: "PolicyConcurrence",
	1: "PolicySerial",
}
var Policy_value = map[string]int32{
	"PolicyConcurrence": 0,
	"PolicySerial":      1,
}

func (x Policy) String() string {
	return proto.EnumName(Policy_name, int32(x))
}
func (Policy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_omega_8447e67675a5c903, []int{0}
}

type PubReq struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace" json:"namespace,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topic_name,json=topicName" json:"topic_name,omitempty"`
	Partition            uint32   `protobuf:"varint,3,opt,name=partition" json:"partition,omitempty"`
	HashCode             uint64   `protobuf:"varint,4,opt,name=hash_code,json=hashCode" json:"hash_code,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PubReq) Reset()         { *m = PubReq{} }
func (m *PubReq) String() string { return proto.CompactTextString(m) }
func (*PubReq) ProtoMessage()    {}
func (*PubReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_8447e67675a5c903, []int{0}
}
func (m *PubReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubReq.Unmarshal(m, b)
}
func (m *PubReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubReq.Marshal(b, m, deterministic)
}
func (dst *PubReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubReq.Merge(dst, src)
}
func (m *PubReq) XXX_Size() int {
	return xxx_messageInfo_PubReq.Size(m)
}
func (m *PubReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PubReq.DiscardUnknown(m)
}

var xxx_messageInfo_PubReq proto.InternalMessageInfo

func (m *PubReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PubReq) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *PubReq) GetPartition() uint32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *PubReq) GetHashCode() uint64 {
	if m != nil {
		return m.HashCode
	}
	return 0
}

func (m *PubReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PubRsp struct {
	Status               int32    `protobuf:"zigzag32,1,opt,name=status" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PubRsp) Reset()         { *m = PubRsp{} }
func (m *PubRsp) String() string { return proto.CompactTextString(m) }
func (*PubRsp) ProtoMessage()    {}
func (*PubRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_8447e67675a5c903, []int{1}
}
func (m *PubRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubRsp.Unmarshal(m, b)
}
func (m *PubRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubRsp.Marshal(b, m, deterministic)
}
func (dst *PubRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubRsp.Merge(dst, src)
}
func (m *PubRsp) XXX_Size() int {
	return xxx_messageInfo_PubRsp.Size(m)
}
func (m *PubRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PubRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PubRsp proto.InternalMessageInfo

func (m *PubRsp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PubRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SubReq struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	Topic                string   `protobuf:"bytes,3,opt,name=topic" json:"topic,omitempty"`
	Group                string   `protobuf:"bytes,4,opt,name=group" json:"group,omitempty"`
	MaxRetryCount        uint32   `protobuf:"varint,5,opt,name=max_retry_count,json=maxRetryCount" json:"max_retry_count,omitempty"`
	MaxTimeout           uint32   `protobuf:"varint,6,opt,name=max_timeout,json=maxTimeout" json:"max_timeout,omitempty"`
	RetryIntervalMs      uint32   `protobuf:"varint,7,opt,name=retry_interval_ms,json=retryIntervalMs" json:"retry_interval_ms,omitempty"`
	ItemLifetimeIn_Queue uint32   `protobuf:"varint,8,opt,name=item_lifetime_in_Queue,json=itemLifetimeInQueue" json:"item_lifetime_in_Queue,omitempty"`
	Policy               Policy   `protobuf:"varint,9,opt,name=policy,enum=omega.Policy" json:"policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *SubReq) Reset()         { *m = SubReq{} }
func (m *SubReq) String() string { return proto.CompactTextString(m) }
func (*SubReq) ProtoMessage()    {}
func (*SubReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_8447e67675a5c903, []int{2}
}
func (m *SubReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubReq.Unmarshal(m, b)
}
func (m *SubReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubReq.Marshal(b, m, deterministic)
}
func (dst *SubReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubReq.Merge(dst, src)
}
func (m *SubReq) XXX_Size() int {
	return xxx_messageInfo_SubReq.Size(m)
}
func (m *SubReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SubReq.DiscardUnknown(m)
}

var xxx_messageInfo_SubReq proto.InternalMessageInfo

func (m *SubReq) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *SubReq) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SubReq) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SubReq) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *SubReq) GetMaxRetryCount() uint32 {
	if m != nil {
		return m.MaxRetryCount
	}
	return 0
}

func (m *SubReq) GetMaxTimeout() uint32 {
	if m != nil {
		return m.MaxTimeout
	}
	return 0
}

func (m *SubReq) GetRetryIntervalMs() uint32 {
	if m != nil {
		return m.RetryIntervalMs
	}
	return 0
}

func (m *SubReq) GetItemLifetimeIn_Queue() uint32 {
	if m != nil {
		return m.ItemLifetimeIn_Queue
	}
	return 0
}

func (m *SubReq) GetPolicy() Policy {
	if m != nil {
		return m.Policy
	}
	return Policy_PolicyConcurrence
}

type SubRsp struct {
	Status               int32    `protobuf:"zigzag32,1,opt,name=status" json:"status,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *SubRsp) Reset()         { *m = SubRsp{} }
func (m *SubRsp) String() string { return proto.CompactTextString(m) }
func (*SubRsp) ProtoMessage()    {}
func (*SubRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_8447e67675a5c903, []int{3}
}
func (m *SubRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubRsp.Unmarshal(m, b)
}
func (m *SubRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubRsp.Marshal(b, m, deterministic)
}
func (dst *SubRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubRsp.Merge(dst, src)
}
func (m *SubRsp) XXX_Size() int {
	return xxx_messageInfo_SubRsp.Size(m)
}
func (m *SubRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SubRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SubRsp proto.InternalMessageInfo

func (m *SubRsp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SubRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ConsumeReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Sequence             uint64   `protobuf:"varint,2,opt,name=sequence" json:"sequence,omitempty"`
	IsRetry              bool     `protobuf:"varint,3,opt,name=is_retry,json=isRetry" json:"is_retry,omitempty"`
	IgnoreRetryCount     bool     `protobuf:"varint,4,opt,name=ignore_retry_count,json=ignoreRetryCount" json:"ignore_retry_count,omitempty"`
	RetryIntervalMs      int64    `protobuf:"zigzag64,5,opt,name=retry_interval_ms,json=retryIntervalMs" json:"retry_interval_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ConsumeReq) Reset()         { *m = ConsumeReq{} }
func (m *ConsumeReq) String() string { return proto.CompactTextString(m) }
func (*ConsumeReq) ProtoMessage()    {}
func (*ConsumeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_8447e67675a5c903, []int{4}
}
func (m *ConsumeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeReq.Unmarshal(m, b)
}
func (m *ConsumeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeReq.Marshal(b, m, deterministic)
}
func (dst *ConsumeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeReq.Merge(dst, src)
}
func (m *ConsumeReq) XXX_Size() int {
	return xxx_messageInfo_ConsumeReq.Size(m)
}
func (m *ConsumeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeReq.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeReq proto.InternalMessageInfo

func (m *ConsumeReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ConsumeReq) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ConsumeReq) GetIsRetry() bool {
	if m != nil {
		return m.IsRetry
	}
	return false
}

func (m *ConsumeReq) GetIgnoreRetryCount() bool {
	if m != nil {
		return m.IgnoreRetryCount
	}
	return false
}

func (m *ConsumeReq) GetRetryIntervalMs() int64 {
	if m != nil {
		return m.RetryIntervalMs
	}
	return 0
}

type ConsumeRsp struct {
	Partition            uint32   `protobuf:"varint,2,opt,name=partition" json:"partition,omitempty"`
	Sequence             uint64   `protobuf:"varint,3,opt,name=sequence" json:"sequence,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	RetryCount           uint32   `protobuf:"varint,5,opt,name=retry_count,json=retryCount" json:"retry_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ConsumeRsp) Reset()         { *m = ConsumeRsp{} }
func (m *ConsumeRsp) String() string { return proto.CompactTextString(m) }
func (*ConsumeRsp) ProtoMessage()    {}
func (*ConsumeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_omega_8447e67675a5c903, []int{5}
}
func (m *ConsumeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeRsp.Unmarshal(m, b)
}
func (m *ConsumeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeRsp.Marshal(b, m, deterministic)
}
func (dst *ConsumeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeRsp.Merge(dst, src)
}
func (m *ConsumeRsp) XXX_Size() int {
	return xxx_messageInfo_ConsumeRsp.Size(m)
}
func (m *ConsumeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeRsp proto.InternalMessageInfo

func (m *ConsumeRsp) GetPartition() uint32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *ConsumeRsp) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ConsumeRsp) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ConsumeRsp) GetRetryCount() uint32 {
	if m != nil {
		return m.RetryCount
	}
	return 0
}

func init() {
	proto.RegisterType((*PubReq)(nil), "omega.PubReq")
	proto.RegisterType((*PubRsp)(nil), "omega.PubRsp")
	proto.RegisterType((*SubReq)(nil), "omega.SubReq")
	proto.RegisterType((*SubRsp)(nil), "omega.SubRsp")
	proto.RegisterType((*ConsumeReq)(nil), "omega.ConsumeReq")
	proto.RegisterType((*ConsumeRsp)(nil), "omega.ConsumeRsp")
	proto.RegisterEnum("omega.Policy", Policy_name, Policy_value)
}

func init() { proto.RegisterFile("omega.proto", fileDescriptor_omega_8447e67675a5c903) }

var fileDescriptor_omega_8447e67675a5c903 = []byte{
	// 606 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xcb, 0x6e, 0x13, 0x31,
	0x14, 0xad, 0xd3, 0x34, 0xc9, 0xdc, 0x36, 0x34, 0x31, 0x50, 0x0d, 0x2d, 0x88, 0x68, 0x24, 0x50,
	0x54, 0xa1, 0x06, 0xda, 0xc2, 0x82, 0x25, 0x59, 0x55, 0xe2, 0x51, 0x1c, 0x56, 0x6c, 0x46, 0xce,
	0xc4, 0x24, 0x16, 0xe3, 0xf1, 0xd4, 0x8f, 0xaa, 0x15, 0x9f, 0x01, 0x7f, 0xc2, 0x0f, 0xf0, 0x69,
	0xc8, 0xf6, 0xe4, 0x59, 0xc4, 0x6e, 0xee, 0x39, 0xc7, 0x57, 0xf7, 0x9c, 0x7b, 0x35, 0xb0, 0x2b,
	0x05, 0x9b, 0xd2, 0x93, 0x52, 0x49, 0x23, 0xf1, 0x8e, 0x2f, 0x92, 0x5f, 0x08, 0x1a, 0x97, 0x76,
	0x4c, 0xd8, 0x15, 0x7e, 0x0c, 0x51, 0x41, 0x05, 0xd3, 0x25, 0xcd, 0x58, 0x8c, 0x7a, 0xa8, 0x1f,
	0x91, 0x25, 0x80, 0x9f, 0x00, 0x18, 0x59, 0xf2, 0x2c, 0x75, 0x50, 0x5c, 0x0b, 0xb4, 0x47, 0x3e,
	0x52, 0xc1, 0xdc, 0xe3, 0x92, 0x2a, 0xc3, 0x0d, 0x97, 0x45, 0xbc, 0xdd, 0x43, 0xfd, 0x36, 0x59,
	0x02, 0xf8, 0x08, 0xa2, 0x19, 0xd5, 0xb3, 0x34, 0x93, 0x13, 0x16, 0xd7, 0x7b, 0xa8, 0x5f, 0x27,
	0x2d, 0x07, 0x0c, 0xe5, 0x84, 0x61, 0x0c, 0xf5, 0x09, 0x35, 0x34, 0xde, 0xe9, 0xa1, 0xfe, 0x1e,
	0xf1, 0xdf, 0xc9, 0xdb, 0x30, 0x95, 0x2e, 0xf1, 0x01, 0x34, 0xb4, 0xa1, 0xc6, 0x6a, 0x3f, 0x52,
	0x97, 0x54, 0x15, 0x8e, 0xa1, 0x29, 0x98, 0xd6, 0x74, 0x3a, 0x1f, 0x66, 0x5e, 0x26, 0x7f, 0x6a,
	0xd0, 0x18, 0x05, 0x4b, 0x47, 0x10, 0x65, 0x39, 0x67, 0x85, 0x49, 0xf9, 0xa4, 0xb2, 0xd4, 0x0a,
	0xc0, 0xc5, 0x64, 0xdd, 0x6f, 0x6d, 0xd3, 0xef, 0x03, 0xd8, 0xf1, 0xee, 0xbc, 0x99, 0x88, 0x84,
	0xc2, 0xa1, 0x53, 0x25, 0x6d, 0xe9, 0x4d, 0x44, 0x24, 0x14, 0xf8, 0x39, 0xec, 0x0b, 0x7a, 0x93,
	0x2a, 0x66, 0xd4, 0x6d, 0x9a, 0x49, 0x5b, 0x18, 0x6f, 0xa6, 0x4d, 0xda, 0x82, 0xde, 0x10, 0x87,
	0x0e, 0x1d, 0x88, 0x9f, 0xc2, 0xae, 0xd3, 0x19, 0x2e, 0x98, 0xb4, 0x26, 0x6e, 0x78, 0x0d, 0x08,
	0x7a, 0xf3, 0x25, 0x20, 0xf8, 0x18, 0xba, 0xa1, 0x09, 0x2f, 0x0c, 0x53, 0xd7, 0x34, 0x4f, 0x85,
	0x8e, 0x9b, 0x5e, 0xb6, 0xef, 0x89, 0x8b, 0x0a, 0xff, 0xa0, 0xf1, 0x19, 0x1c, 0x70, 0xc3, 0x44,
	0x9a, 0xf3, 0x6f, 0xcc, 0x75, 0x4c, 0x79, 0x91, 0x7e, 0xb6, 0xcc, 0xb2, 0xb8, 0xe5, 0x1f, 0xdc,
	0x77, 0xec, 0xfb, 0x8a, 0xbc, 0x28, 0x3c, 0x85, 0x9f, 0x41, 0xa3, 0x94, 0x39, 0xcf, 0x6e, 0xe3,
	0xa8, 0x87, 0xfa, 0xf7, 0x4e, 0xdb, 0x27, 0xe1, 0x26, 0x2e, 0x3d, 0x48, 0x2a, 0x32, 0x79, 0x13,
	0x12, 0xfc, 0x4f, 0xfc, 0x3e, 0x9e, 0xef, 0xac, 0xa8, 0x82, 0x0b, 0x45, 0xf2, 0x1b, 0x01, 0x0c,
	0x65, 0xa1, 0xad, 0x60, 0x2e, 0xfe, 0x85, 0x08, 0xad, 0x88, 0xf0, 0x21, 0xb4, 0x34, 0xbb, 0xb2,
	0xac, 0xa8, 0x62, 0xaf, 0x93, 0x45, 0x8d, 0x1f, 0x41, 0x8b, 0xeb, 0x10, 0xa4, 0x0f, 0xbe, 0x45,
	0x9a, 0x5c, 0xfb, 0x04, 0xf1, 0x0b, 0xc0, 0x7c, 0x5a, 0x48, 0xc5, 0xd6, 0x72, 0xae, 0x7b, 0x51,
	0x27, 0x30, 0x2b, 0x51, 0xff, 0x33, 0x49, 0xb7, 0x14, 0x7c, 0x27, 0xc9, 0xe4, 0xc7, 0x72, 0x68,
	0x5d, 0xae, 0x5f, 0x72, 0x6d, 0xf3, 0x92, 0x57, 0x87, 0xdf, 0xde, 0x18, 0x7e, 0x7e, 0xc8, 0xf5,
	0xe5, 0x21, 0xbb, 0x95, 0xdf, 0x3d, 0x0b, 0x50, 0x8b, 0x41, 0x8f, 0x5f, 0x41, 0x23, 0x84, 0x8f,
	0x1f, 0x42, 0x37, 0x7c, 0x0d, 0x65, 0x91, 0x59, 0xa5, 0x5c, 0xcf, 0xce, 0x16, 0xee, 0xc0, 0x5e,
	0x80, 0x47, 0x4c, 0x71, 0x9a, 0x77, 0xd0, 0xe9, 0x4f, 0x04, 0x7b, 0x9f, 0xdc, 0xda, 0x46, 0x4c,
	0x5d, 0xf3, 0xcc, 0x6d, 0x75, 0xfb, 0xd2, 0x8e, 0xf1, 0x62, 0x99, 0xfe, 0xf8, 0x0f, 0x57, 0x4b,
	0x5d, 0x26, 0x5b, 0x4e, 0x36, 0x5a, 0x91, 0x8d, 0xd6, 0x65, 0xa3, 0xb9, 0xec, 0x35, 0x34, 0xab,
	0x38, 0x70, 0xb7, 0xe2, 0x96, 0x3b, 0x3d, 0xdc, 0x84, 0xdc, 0x93, 0x3e, 0x7a, 0x89, 0xde, 0x25,
	0x5f, 0x7b, 0x53, 0x6e, 0x66, 0x76, 0x7c, 0x92, 0x49, 0x31, 0x10, 0xf9, 0xf9, 0xf9, 0xf9, 0x40,
	0x67, 0x33, 0x36, 0xb1, 0x39, 0x53, 0x83, 0x72, 0x3c, 0x28, 0xc7, 0xe3, 0x86, 0xff, 0xf7, 0x9c,
	0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xed, 0x4a, 0xf4, 0xa7, 0x8a, 0x04, 0x00, 0x00,
}
